# Copyright 2019, IBM.
#
# This source code is licensed under the Apache License, Version 2.0 found in
# the LICENSE.txt file in the root directory of this source tree.

dist: xenial

language: python

python:
  - "3.7.4"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost-program-options-dev
    - libmpfrc++-dev

install:
  - pip install --upgrade pip
  - pip install "qiskit>=0.8"
  - pip install -r requirements-dev.txt

matrix:
  include:
  - name: style
    script:
    - make style
  - name: test Python 3.7
    script:
    - make sim
    - make test
